### PR TITLE
README.md; standard/: Changes to reflect implications of OGC API - Co…

### PR DESCRIPTION
**Pull request by jerstlouis**
…mmon - Part 2: Geospatial data

- As discussed in https://github.com/opengeospatial/ogc_api_coverages/issues/64
- Other clarifications
- Also edited for completeness (e.g. Communication, Contributions)

### CODE REVIEW

**Comment by jerstlouis** [comment]
1. Reflect the main changes discussed in issue #64:

    - /coverage is now what /coverage/all was
    - /coverage/all is gone
    - /coverage/description is gone
    - /coverage/rangetype and /coverage/domainset are not required, if they are a property of the {collectionId} resource
    - The envelope is now the extent in /collections/{collectionId} resource
    - /coverage/metadata and /coverage/rangeset are no longer required

    This allows a simple implementation with only  /collections/{collectionId} and /collections/{collection}/coverage resources

2. Remove this concept of a default encoding. That was problematic.

   - There should not be any default encoding.
   - At minimum a CIS JSON encoding of range type and domainset are required, and if set as {collectionId} properties that's what those must be.
   - If no content negotiation is done (no HTTP header), the media type is what the link says it is. In a sense I would argue that's still "content negotiation" because you are following a link for which you now the media type.

3. Change {root} to {datasetAPI}

    - In summary, Features says OGC distribution APIs should work on a single DCAT dataset / distribution. A service though can offer many datasets, and processing can act on many datasets together.
    - Therefore I think we need both Service-wide API landing pages, and Datasets API landing pages
    - This is the topic of https://github.com/opengeospatial/oapi_common/issues/120
    - Following discussion in Processing SWG, Peter Vretanos setup this nice OGC API tree page demonstrating how this could look like: https://eratosthenes.pvretano.com/Projects/tb16/ogcapi/datastores.html
    - In our Modular OGC API Workflow project we are planning to adopt this approach.
    - This means that both Service-wide and Dataset API landing pages should be standardized. Common - Core could be applicable to both.
    - In addition to /collections and /collections/{collectoinId}, different requirement classes in Common - GeoData could define how one links to a list of datasets from a landing page, how one lists those datasets, and how one identifies an API as distributing a dataset.

4. Relation types

    - Link to the relation types registry: http://www.opengis.net/def/rel/
    - I think we really need to define clear relation types for each different available resource defined by OGC API standards, and give less important to this idea that we should re-use as much as possible the same relation in totally different contexts with totally different meanings, when we are relying on those relation types trying (from a client's perspective) to clearly and uambiguously identify what a link points to, as it will just cause more and more problems.
    - Among other things this solves the 'itemType' we discussed today in https://github.com/opengeospatial/ogc_api_coverages/issues/65 and also previously discussed in monster issue https://github.com/opengeospatial/oapi_common/issues/140
    - We can still use relative relation types in a few places, e.g. like "self" and "alternate", where they make sense.
    - I like this "ogc:{standard}:{resource}" nomenclature, e.g. "ogc:common:collection" for linking to a /collections/{collectionId} resource.
    - Probably things that should be discussed in Common.

5. Conformance classes reorganization

    - Previously, there was only a Coverages Part 1: Core - Core conformance class. Naming both the part and the conformance class core was problematic, especially when Common also has a Core part (and Core conformance class as well?)
    - I followed a pattern we have been adopting in OGC API - Tiles, e.g. GeoData-Tileset, and propose to name the main Coverage: Core conformance class "GeoData-Coverage", as its purpose is to enable access to GeoData (aka a collection resource), as a coverage
    - The bbox requirement on the collections was a requirement of that Core, and that was problematic. I moved that to its own conformance class as "geodata-filteredList", with bbox, dateTime and limit requirements. I also removed mention that this can be applied to a single {collectionId}, as that does not really make much sense at all since it that resource has a single extent. We could discuss whether all of those should be within the same conformance class. This really is a Common-Part 2 topic though that we shouldn't focus on too much in Coverages.
    - I separated out other core requirements that are from common, which I think also need further work as they refer still non-existing conformance class originally intended for Features. That's common-core.
    - For subsetting the Coverage data itself, I moved this into its own "Coverage-subset" conformance class.
    - I also added Coverage-bbox and Coverage-dateTime for filtering the coverage data based on building blocks defined in Common-GeoData. I think this would go a long way in achieving consistency across the APIs and making the Coverages API easier to approach for a large number of users. Those would be optional conformance classes, separate from subset.
    - I renamed the "JSON" conformance class to "cisjson", as it specifically deals with the CIS JSON encoding of coverages. I also renamed any dependency to a common "geojson" conformance class, as it is the "json" conformance class that should be depended upon.
    - We could discuss whether Coverage-bbox and Coverage-dateTime could be combined in a single conformance class, and also I would eventually like to add Coverage-resolution to this (width & height), but that should probably sit on its own as it might be more difficult to select a different resolution than simply cut the data). All of these I think should be shared with Maps, and even Features to some extent (which would need a clip vs. intersect nuance though), and consequently they would make a generic API - Tiles very easy to implement as face on top of an arbitrary Coverage, Features, or Maps API that supports GeoData-bbox, GeoData-resolution (and GeoData-dateTime for time aspect as well).

    - In summary Coverages - Part 1: Core now define these new conformance classes:
        - GeoData-coverage  -- Basic coverage support
        - Coverage-subset       -- WCS-style SUBSET parameter
        - Coverage-bbox          -- Common BBOX parameter for coverage itself
        - Coverage-dateTime -- Common dateTime parameter for coverage itself
        - cisjson                       -- A testable encoding based on CIS JSON
        - html                           -- HTML encoding conformance class for coverages

    - Purely Common - Part 1: Core conformance classes (nothing at all about coverages in here)
          - common-core         -- Part 1: Core (Core) conformance class
          - oas30                       -- OpenAPI 3.0 conformance

    - Purely Common - Part 2: Geospatial Data classes (nothing at all about coverages in here)
          - GeoData-filteredList  -- Ability to use BBOX and/or DateTime parameter on the list of Collections

     - Note that have not yet create new clauses for the new conformance classes and would probably need to do so for:
         - Coverage-bbox & Coverage-dateTime    -- These probably need a coverage-specific description here and their own clause(s) (There are currently some things about these in Clause 7, but it is ambiguous whether they are about Geodata-filteredList or these)
         - Geodata-filteredList                                 -- This one really belongs in Common - Part 2: Geospatial Data (nothing specific to coverage), so we may want to omit it altogether from Coverage, but we need to set it up in Common, and still need to clean up anything about ?bbox= on collections in Clause 7

6.  Media type section tweaks

    - There were many references to MIME types, which should now be called media types
    - I removed many confusing references to GeoJSON. Coverages API has very little to do with GeoJSON, and GeoJSON is not really a proper encoding for Coverages (not one we need to mention anyways)
    - I added a few recommended encodings as well

7. README update

    - The README is the first thing I saw looking at the repo, and what it was saying was no longer accurate.
    - By fixing it up, I ended up adding more content than perhaps should be there.
    - It might be a good starting basis for a developer's guide, as I think it does now clearly communicate how the API works and is almost everything you need to implement it. Perhaps some of it could also move to Clause 6 Overview.
    - Perhaps some of that content could be summarized or a table like that of Clause 6 - Overview might be better suited in the README
    - These would be good things to discuss if we have a chance to have a working meeting on the topic of this PR

8. Questions about actual range of the data values

    - Nowhere does it seem possible to get actual information about the range of the data values that one can find in a coverage (e.g. minimum / maximum elevation values).
    - I would have expected the range type to have (at least optional) information about this, but apparently that's not the case. Can that be done with CIS, or added as new functionality?
    - Related question about how to define non-standard units, e.g. when a datatype's full range maps to a given range. For example GeoPackage gridded coverage extension can support this.
    - I left some TODOs in the README about these questions

**Comment by pomakis** [comment]
Wow, nicely done, @jerstlouis !

CubeWerx's test implementation at https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa already mostly aligns with these changes.  I'll endeavour to align our implementation even more before the Coverages Sprint.

**Comment by cmheazel** [comment]
Hearing no objections, this PR was merged into Master on August 3, 2020.

**Comment by pebau** [comment]
impressive work, @jerstlouis !

FWIW, if additional information is to be kept the metadata section is always available. For example, redundant information to be kept for efficiency (min/max), EU INSPIRE metadata, etc.

Re units (uom): Like CRSs this constitutes a reference to something OGC-NA once wanted to do: an ontology of units. While that has not happened the URL can reference anything that's useful. Maybe some future work item? Semantic Web world would certainly benefit, too.

Generally, the range type is a 1:1 adoption from SWE Common to allow carrying over sensor semantics without loss of information, for example when doing an upstream SOS sampling of what is then served downstream via WCS.

**Pull request merged**
